### ISSUE TITLE
Custom colours

### ISSUE THREAD

**Issue by lucypoulton** [VladimirWrites/AnalogWatchFace#14]
It'd be nice to be able to set custom colours instead of choosing from a list.

**Comment by VladimirWrites** [comment]
Hi Lucy,

Thank you very much for using the watch face and for proposing the feature.

This feature is on my list of features to add. Right now I don't have a lot of free time to implement it, but it should be there by the end of the year. In any case, I will let you know here when the feature gets released.

**Comment by VladimirWrites** [comment]
Hi Lucy,

I just wanted to provide you with an update. Things didn't go as planned. I didn't have much free time last year, and I also just changed my employer. I don't have time to work on this feature right now, and to be honest, I am not sure when I will be able to add it.

**Comment by houmik** [comment]
Hello guys,

Damn, What a shame - It would be an amazing addition for an already amazing face watch. I wish I could help somehow but my knowledge about app making is very limited :(

**Comment by VladimirWrites** [comment]
The option to add custom colors is added in this commit: 6b6d4bd08a2098700a2a0927abe23707e5ab2cc6  🥳
It will be available in the next release which should be live in a couple of days.
I decided to use 3 sliders for the red, green, and blue channels. It's not perfect but it works :).
There is also an option to delete colors that you don't like by long-pressing the color. ;) 

| Square | Round|
| ----------- | ----------- |
|![Screenshot_1647201549](https://user-images.githubusercontent.com/5979600/158076803-46106109-2910-4a8a-b314-2829b86f11cb.png) | ![Screenshot_1647201524](https://user-images.githubusercontent.com/5979600/158076811-f51eb320-554f-4031-b8bb-c77c51d3d62b.png)|
|![Screenshot_1647201560](https://user-images.githubusercontent.com/5979600/158076823-f3d9e86b-f6c1-4e70-a3e2-4ad5f1792f37.png) | ![Screenshot_1647201538](https://user-images.githubusercontent.com/5979600/158076832-07e05434-8a4c-4c2a-a54a-71de96181b22.png) |
| ![Screenshot_1647201545](https://user-images.githubusercontent.com/5979600/158076843-76f37e5a-6d7d-46d8-af48-1a2643e56b5a.png) | ![Screenshot_1647201545](https://user-images.githubusercontent.com/5979600/158076852-8128a08a-dcec-45eb-bdbb-a7a1efde9f7c.png) |
