### ISSUE TITLE
battery level - circle

### ISSUE THREAD

**Issue by OndrejLeho** [VladimirWrites/AnalogWatchFace#23]
Hi Vladimir,
after a long journey I've finaly found your app which exactly meets my needs and expectations. Good job, thank you.

Everything works fine, just two things:
1) On my Samsung Galaxy Watch4 Classic, 46mm I've set the battery level indicator where I can see how much % of battery **remains**, there is also a bow (= part of a circle) around which indicates how much energy **is used**. The more energy used the longer is the bow. When there is 0% of battery left, so the bow would be a full circle 360°. So there are two contrary parameters about battery energy. 
My request: I'd rather have two equal indications: number in % how much battery remains + circle which would also indicate how much battery remains. So if I have 100% battery, the circle would be 360°.
2) On my wife's Samsung Galaxy Watch4, 40mm there is no bow/circle around the battery level indicator at all. I guess this is due to less display resolution of the smaller Watch4, 40 mm version, right?
Both me and my wife aren't young people anymore, our eyes don't work well anymore. Besides % of battery we need also optical battery level indicator - bow/circle which is great to see on locked screen too!
Could you please fix it?
3) One more question: I'd welcome bigger characters (numbers) of complications - in our case is it Datum and Battery level.
Sure I've set the option "Use bigger text" but I'd be happy if the text could be even bigger.

Please see attached picture of the watch of mine and my wife.
Keep going in good work. Whishing all the best
Ondrej
![DSC_5352](https://user-images.githubusercontent.com/94743995/142726008-33c93e81-335c-4b29-8a41-5a5d06e7463d.JPG)

**Comment by VladimirWrites** [comment]
Hi Ondrej! 

Thank you very much for using the watch face. :)

1. Could you try playing with `Complication Ranged Value Primary Color` and `Complication Ranged Value Secondary Color` in Settings -> Complications Settings -> Complication Colors? In the battery example, the primary value represents the amount of battery available (42% on the picture), and the secondary value represents the spent amount of battery (58% on battery). It seems that in your case the primary value is set to black or transparent.

2. Could you please check  `Complication Ranged Value Primary Color` and `Complication Ranged Value Secondary Color` on your wife's watch as well. It should be working on smaller watches, so my guess is that these two values are set to either black or transparent.

3. I already got a request for this feature, and I tried to solve it a couple of times. Sadly the library that I am using to present complications doesn't support this adjustment. Google is releasing a new major version of this library soon, so this feature may be supported in the near future, once the stable version of this library is available and I migrate to it.

Best,
Vladimir

**Comment by OndrejLeho** [comment]
Hi Vladimir!
Issues 1) + 2) solved, thanx!
3) Not a great issue but woud be nice to have solved. I'll be pleased if you'll let me know then.

Thanx again
Ondrej

**Comment by VladimirWrites** [comment]
Great! :) I will let you know when I fix it.
I will close this issue for now, as I already have that feature in my todos.

**Comment by Der-Schubi** [comment]
Hi Vladimir!
Are there any news regarding the bigger font for complications?
I've set time & date for top complication and would love to have the time a bit bigger as in many semi-digital watchfaces.

**Comment by VladimirWrites** [comment]
Hi! Sorry but still nothing new. I am still migrating to the latest Google libraries. I am struggling a lot to replicate all the functionality with these new libs. I can't promise anything in the next couple of months.
You can expect new features to be added after version 3.0.0 is released.
