### ISSUE TITLE
"Day and Date" complication doesn't show Day

### ISSUE THREAD

**Issue by matt-winfield** [VladimirWrites/AnalogWatchFace#29]
Using Samsung Galaxy Watch 4, the "Day and Date" complication now no longer includes the day, and instead shows a calendar icon.

Not sure if this change was caused by an update to the watch face (perhaps fixing https://github.com/VladimirWrites/AnalogWatchFace/issues/22?) or a Samsung update, it's been like this for a few months (sorry I didn't raise it earlier!).

**Comment by VladimirWrites** [comment]
Thank you very much for creating the issue, and sorry for the late answer. 
Samsung introduced the issue with one of their updates. They are controlling which data is being presented in complications, and I am just allowing users to choose data provider for a specific place.
Currently, I am migrating to new Google libraries, so maybe when that's done, the integration with Samsung improves a bit. But as it's right now, there is not much that I can do without introducing a lot of code for every update that Samsung provides.
