### ISSUE TITLE
Current heart rate not shown on Galaxy Watch 5

### ISSUE THREAD

**Issue by guger** [VladimirWrites/AnalogWatchFace#37]
Hi there!

I really like your analog watch face, since I was looking for a sleek, customizable UI with some complications.

Unfortunately, on my Galaxy Watch 5, the heart rate complication does not show the current heart rate, but only an icon.

Is this currently not implemented, as I read in your description, that some Samsung device features are not available?

Are there any updates or can I help you with realising this?

**Comment by VladimirWrites** [comment]
Hi! Thank you very much for your kind words. 
It's the limitation that Samsung and Google impose on 3rd party watch faces (for some reason). There are some workarounds that some watch faces have implemented, but I just don't have time to incorporate and support that functionality. If you want that feature you can use this paid app that exposes heart rate complications to 3rd party watch faces: https://play.google.com/store/apps/details?id=com.weartools.heartratecomp.
I don't know if there is a free solution for this, and if you find it please let me know.
