### ISSUE TITLE
[Feature Request] Support Rotary Input

### ISSUE THREAD

**Issue by Domi04151309** [VladimirWrites/AnalogWatchFace#4]
Adding support for rotary input to scroll the configuration pages would be a nice thing to have.

**Comment by VladimirWrites** [comment]
Sure! This sounds like a nice feature. 👍 
I won't have time to work on this for the next couple of weeks. If you have time feel free to submit a pull request.

**Comment by Domi04151309** [comment]
I'd be happy to submit a pull request but I'll wait until you've merged the open one.
