### ISSUE TITLE
Pro Trek

### ISSUE THREAD

**Issue by JVRyder** [VladimirWrites/AnalogWatchFace#8]
Hi Vladimir 
I have a Casio Protrek WSD-F21HR-RDBGB 
It has the Flat Tyre screen design.
Is it possible to adjust your excellent watch face to accommodate this by zooming the dial or creating a larger border around the circumference.
Thanks 
Jonathan 
![16277333404067962675828127414140](https://user-images.githubusercontent.com/88236231/127739419-2ac470b0-7452-4689-a4e7-fbd0257bea30.jpg)

**Comment by VladimirWrites** [comment]
Hi,

Thanks for using the watch face 😊!
To be honest I was hoping that I will not have users with the chin (flat tire) watch. 😅

I will first try to make the ticks follow the shape of the watch so that at the bottom, they would follow the chin. If that doesn't work I will add the option that you suggested, to zoom the whole watch face out, so it fits on the screen.

Best,
Vladimir

**Comment by JVRyder** [comment]
Thankyou and good luck
👍

**Comment by VladimirWrites** [comment]
@JVRyder I just want to let you know that I am still working on this feature, and sadly I will not be able to ship it with the next release.

**Comment by VladimirWrites** [comment]
Does this look like something that you had in mind? If it looks good to you I will have a release ready by the end of the week.

| Ticks 1  | Ticks 2  | Ticks 3  | Ticks 4  | 
|---|---|---|---|
| ![Screenshot_1630478322](https://user-images.githubusercontent.com/5979600/131623879-c921c3a5-5646-4e4e-acdd-dddddbe25c97.png)  | ![Screenshot_1630478303](https://user-images.githubusercontent.com/5979600/131623888-78b99e5f-bd62-4b2f-9da2-4bbd7662a596.png)  | ![Screenshot_1630478278](https://user-images.githubusercontent.com/5979600/131623891-294f4c3d-9523-495d-92b9-a33af557eb50.png)  | ![Screenshot_1630478020](https://user-images.githubusercontent.com/5979600/131623896-b91e5451-0a50-40f2-a70b-3c117f9a36f9.png)  |

**Comment by JVRyder** [comment]
HiThat is it !Brilliant Thankyou very muchThis should be the best face for the flat tyre.Thankyou rgdsJonathan 
-------- Original message --------From: Vladimir Jovanović ***@***.***> Date: 01/09/2021  07:43  (GMT+00:00) To: VladimirWrites/AnalogWatchFace ***@***.***> Cc: JVRyder ***@***.***>, Mention ***@***.***> Subject: Re: [VladimirWrites/AnalogWatchFace] Pro Trek (#8) 
Does this look like something that you had in mind? If it looks good to you I will have a release ready by the end of the week.



Ticks 1
Ticks 2
Ticks 3
Ticks 4

**Comment by VladimirWrites** [comment]
Fixed by https://github.com/VladimirWrites/AnalogWatchFace/commit/dd146a1b2a07178e95b5f01e84c721da540eb19b
